apiVersion: apps/v1
kind: Deployment
metadata:
name: hello
labels:
  app: hello
spec:
strategy:
  type: Recreate
template:
  metadata:
    labels:
      app: hello
      tier: hello
  spec:
    containers:
    - name: hello
      image: ashish362/docker-demo:cucumberhello
      imagePullPolicy: Always
      ports:
      - containerPort: 2020
        name: hello

---

apiVersion: v1
kind: Service
metadata:
name: hello
labels:
  app: hello
spec:
ports:
  - port: 2020
    targetPort: 2020
selector:
  app: hello
  tier: hello
type: LoadBalancer
