apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cucumberhello
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: cucumberhello
    spec:
      containers:
        - name: cucumberhello
          image: gcr.io/internal-investment-206615/cucumberhello
          ports:
            - containerPort: 2020

---

apiVersion: v1
kind: Service
metadata:
  name: cucumberhello-service
  labels:
    name: cucumberhello-service
spec:
  ports:
    - port: 2020
      targetPort: 2020
      protocol: TCP
  selector:
    app: cucumberhello
  type: LoadBalancer


